- .github/workflows/docker.yml
- backend/auth/auth-api/k8/base/deployment.yaml
- backend/auth/auth-api/k8/overlays/minikube/never-pull-image-policy.yaml
- backend/auth/auth-api/migrations/manifests.yaml
- backend/beacon/beacon-api/k8/base/deployment.yaml
- backend/beacon/beacon-api/k8/overlays/development/never-pull-image-policy.yaml
- backend/events/search-indexer/k8/deployment.yaml
- backend/local-test-services/README.md
- backend/local-test-services/Tiltfile
- backend/session/session-api/k8/base/deployment.yaml
- backend/session/session-api/k8/overlays/development/never-pull-image-policy.yaml
- backend/session/session-api/migrations/manifests.yaml
- frontend/app/k8/base/deployment.yaml
- frontend/app/k8/overlays/development/never-pull-image-policy.yaml
need to add all images and update yamls to refence them
> Build docker

- .github/workflows/docker.yml
- backend/auth/auth-api/k8/base/deployment.yaml
- backend/auth/auth-api/k8/base/ingress.yaml
- backend/auth/auth-api/k8/base/kustomization.yaml
- backend/auth/auth-api/k8/base/migrations.yaml
- backend/auth/auth-api/k8/overlays/minikube/never-pull-image-policy.yaml
- backend/beacon/beacon-api/k8/base/deployment.yaml
- backend/beacon/beacon-api/k8/base/ingress.yaml
- backend/beacon/beacon-api/k8/overlays/development/never-pull-image-policy.yaml
- backend/events/search-indexer/k8/deployment.yaml
- backend/image-pull-secret.patch
- backend/job-generate-name.patch
- backend/kustomization.yaml
- backend/local-test-services/Tiltfile
- backend/session/session-api/k8/base/deployment.yaml
- backend/session/session-api/k8/base/ingress.yaml
- backend/session/session-api/k8/base/kustomization.yaml
- backend/session/session-api/k8/base/migrations.yaml
- backend/session/session-api/k8/overlays/development/never-pull-image-policy.yaml
- infrastructure/k8/dev/helmfile.yaml
- infrastructure/k8/dev/jaeger.yaml
**What**:
**Why**:
**How**:
**Checklist**:
> Docker build #2

- backend/auth/auth-api/k8/base/deployment.yaml
- backend/beacon/beacon-api/k8/base/deployment.yaml
- backend/events/search-indexer/k8/deployment.yaml
- backend/session/session-api/k8/base/deployment.yaml
**What**:
**Why**:
**How**:
**Checklist**:
> Tracing agent url

- infrastructure/k8/dev/grafana.yaml
- infrastructure/k8/dev/helmfile.yaml
- infrastructure/k8/dev/production.yaml
Logs you in to grafana as your github user.
> Pass auth headers to apps that support it.

- backend/auth/auth-api/k8/base/migrations.yaml
- backend/session/session-api/k8/base/migrations.yaml
**What**:
**Why**:
**How**:
**Checklist**:
> Cleanup jobs after completion

- .github/workflows/backend:check.yml
- .github/workflows/backend:test.yml
- .github/workflows/frontend.yml
- .github/workflows/frontend:app.yml
- .github/workflows/frontend:app:storybook.yml
- .github/workflows/frontend:browser:bootstrap.yml
- .github/workflows/frontend:browser:tracking.yml
- .github/workflows/frontend:try.yml
- .github/workflows/frontend:try:storybook.yml
- infrastructure/terraform/modules/browser/main.tf
Because we dynamically fetch bootstrap script, we need to support OPTIONS preflight request. For CORS to work, we also need to forward CORS related headers.
> Cloudfront: fix cors

- backend/shared/rest/build.gradle
- backend/shared/rest/src/main/java/com/meemaw/shared/rest/BooleanFilterExpression.java
- backend/shared/rest/src/main/java/com/meemaw/shared/rest/BooleanOperation.java
- backend/shared/rest/src/main/java/com/meemaw/shared/rest/FilterExpression.java
- backend/shared/rest/src/main/java/com/meemaw/shared/rest/SearchDTO.java
- backend/shared/rest/src/main/java/com/meemaw/shared/rest/SortDirection.java
- backend/shared/rest/src/main/java/com/meemaw/shared/rest/SortQuery.java
- backend/shared/rest/src/main/java/com/meemaw/shared/rest/TermFilterExpression.java
- backend/shared/rest/src/main/java/com/meemaw/shared/rest/TermOperation.java
- backend/shared/rest/src/main/java/com/meemaw/shared/rest/rhs/colon/RHSColonParser.java
- backend/shared/rest/src/test/java/com/meemaw/shared/rest/rhs/RHSColorParserTest.java
Migrate some of the work from https://github.com/Meemaw/Insight/pull/73
Currently implementation is tied to SQL generation as there is an immediate feature that needs it. Once we'll need logic for Elasticsearch and other datasources we can further abstract this.
> feat: rhs colon query to sql

- .github/workflows/docker.yml
- backend/shared/rest/src/main/java/com/meemaw/shared/rest/query/sql/SQLBooleanFilterExpression.java
- backend/shared/rest/src/main/java/com/meemaw/shared/rest/query/sql/SQLFilterExpression.java
- backend/shared/rest/src/main/java/com/meemaw/shared/rest/query/sql/SQLTermFilterExpression.java
- frontend/app/docker/Dockerfile
- frontend/app/package.json
- frontend/app/src/api/base.ts
- frontend/app/src/api/session.ts
- frontend/app/src/modules/sessions/hooks/useSession.ts
- frontend/app/src/modules/sessions/hooks/useSessions.ts
- frontend/app/src/pages/index.tsx
- frontend/app/src/pages/sessions/[id].tsx
- yarn.lock
> frontend(app): fetch & render sessions

- backend/session/session-api/k8/base/deployment.yaml
**What**:
**Why**:
**How**:
**Checklist**:
> fix session api

- infrastructure/k8/development/default.yaml
- infrastructure/k8/development/es.yaml
- infrastructure/k8/development/fluentbit.yaml
- infrastructure/k8/development/helmfile.yaml
- infrastructure/k8/development/production.yaml
- Give more resources to elasticsearch
- change time_key on fluentbit which seems to fix our issues with missing logs
> Feature es resources increase

- backend/events/events-model/src/main/java/com/meemaw/events/model/incoming/AbstractBrowserEvent.java
- backend/events/events-model/src/main/java/com/meemaw/events/model/incoming/BrowserErrorEvent.java
- backend/events/events-model/src/main/java/com/meemaw/events/model/outgoing/dto/AbstractBrowserEventDTO.java
- backend/events/events-model/src/main/java/com/meemaw/events/model/outgoing/dto/BrowserErrorEventDTO.java
- backend/events/events-model/src/main/java/com/meemaw/events/model/shared/BrowserEventType.java
- frontend/app/src/modules/sessions/components/SessionDetails.tsx/SessionDetails.tsx
- frontend/browser/tracking/src/backend/transports/base.ts
- frontend/browser/tracking/src/backend/transports/beacon.ts
- frontend/browser/tracking/src/backend/transports/fetch.ts
- frontend/browser/tracking/src/backend/transports/xhr.ts
- frontend/browser/tracking/src/backend/types.ts
- frontend/browser/tracking/src/console/index.ts
- frontend/browser/tracking/src/event/event.ts
- frontend/browser/tracking/src/index.spec.ts
- frontend/browser/tracking/src/index.ts
- frontend/browser/tracking/src/queue/queue.ts
- frontend/browser/tracking/src/types.ts
- frontend/shared/types/src/event.ts
- Add on error tracking
- Try to use native event timestamp when possible (https://developer.mozilla.org/en-US/docs/Web/API/Event/timeStamp), and "calculate" it only if needed as a fallback
> feat(tracking): on error

- .github/workflows/docker.yml
- backend/auth/auth-api/k8/base/migrations.yaml
- backend/beacon/beacon-api/k8/base/deployment.yaml
- backend/custom_build.sh
- backend/session/session-api/k8/base/ingress.yaml
- backend/session/session-api/k8/base/migrations.yaml
- backend/session/session-api/k8/base/service.yaml
- infrastructure/k8/development/atlantis.yaml
- infrastructure/terraform/github/repositories.tf
- skaffold.yaml
Also specifies dockerfile for custom builds, to let skaffold auto infer dependencies.
> Specifies build args for frontend

- infrastructure/k8/nginx-ingress.yaml
**What**:
**Why**:
**How**:
**Checklist**:
> Ingress source ip

- skaffold.yaml
**What**:
**Why**:
**How**:
**Checklist**:
> fix image names

- backend/billing/billing-api/k8/base/deployment.yaml
- backend/billing/billing-api/src/main/java/com/meemaw/billing/core/App.java
- backend/billing/billing-api/src/main/resources/application.properties
- backend/billing/billing-api/src/test/java/com/meemaw/billing/core/resource/cors/CorsTest.java
- backend/billing/billing-api/src/test/java/com/meemaw/billing/core/resource/health/HealthCheckTest.java
- backend/billing/billing-api/src/test/java/com/meemaw/billing/core/resource/metrics/MetricsTest.java
- backend/billing/billing-api/src/test/java/com/meemaw/billing/core/resource/openapi/OpenApiTest.java
- backend/local-test-services/docker-compose.yml
- backend/session/session-api/k8/base/deployment.yaml
- backend/session/session-api/src/main/resources/application.properties
- backend/session/session-api/src/test/java/com/meemaw/session/core/resource/cors/CorsTest.java
- frontend/shared/sdk/src/billing/subscriptions/resource.ts
- frontend/shared/sdk/src/billing/subscriptions/utils.ts
- frontend/shared/types/src/billing.ts
- frontend/shared/types/src/index.ts
- frontend/shared/types/src/organization.ts
**What**:
**Why**:
**How**:
**Checklist**:
> fix(backend/billing-api): fix port

- backend/billing/billing-api/k8/base/deployment.yaml
- infrastructure/k8/development/atlantis.yaml
- infrastructure/terraform/github/backend.tf
- infrastructure/terraform/github/repositories.tf
- infrastructure/terraform/github/versions.tf
- infrastructure/terraform/management/budget/backend.tf
- infrastructure/terraform/management/budget/providers.tf
- infrastructure/terraform/management/budget/versions.tf
- infrastructure/terraform/modules/billing/main.tf
- infrastructure/terraform/modules/billing/variables.tf
- infrastructure/terraform/modules/billing/versions.tf
- infrastructure/terraform/modules/browser/versions.tf
- infrastructure/terraform/staging/billing/backend.tf
- infrastructure/terraform/staging/billing/data_sources.tf
- infrastructure/terraform/staging/billing/main.tf
- infrastructure/terraform/staging/billing/providers.tf
- infrastructure/terraform/staging/billing/versions.tf
- infrastructure/terraform/staging/browser/backend.tf
- infrastructure/terraform/staging/browser/providers.tf
- infrastructure/terraform/staging/browser/versions.tf
- infrastructure/terraform/staging/dns/backend.tf
- infrastructure/terraform/staging/dns/providers.tf
- infrastructure/terraform/staging/dns/versions.tf
**What**:
**Why**:
**How**:
**Checklist**:
> feat(infra): bump terraform

- infrastructure/terraform/modules/billing/main.tf
- package.json
- yarn.lock
**What**:
**Why**:
**How**:
**Checklist**:
> chore(deps): bump @testing-library/react-hooks

- backend/gradle.properties
- backend/local-test-services/docker-compose.yml
- backend/shared/testing-utils/src/main/java/com/meemaw/test/testconainers/elasticsearch/ElasticsearchTestContainer.java
- infrastructure/k8/development/helmfile.yaml
**What**:
**Why**:
**How**:
**Checklist**:
> chore(deps): bump infras

- frontend/app/src/modules/app/components/Navbar/Banner/Banner.spec.tsx
- frontend/app/src/modules/app/components/Navbar/Banner/Banner.stories.tsx
- frontend/app/src/modules/app/components/Navbar/Banner/Banner.tsx
- frontend/app/src/modules/app/components/Navbar/Banner/BannerCard.tsx
- frontend/app/src/modules/app/components/Navbar/Banner/MenuOptionGroupItem.tsx
- frontend/app/src/modules/settings/pages/SettingsPage/SettingsPage.tsx
- frontend/app/src/test/data/organization.ts
- frontend/app/src/test/data/user.ts
- frontend/shared/next-testing/src/render.tsx
- frontend/shared/types/src/user.ts
**What**:
**Why**:
**How**:
**Checklist**:
> feat(frontend/app): sidebar banner ui fixes

- backend/billing/billing-api/src/main/java/com/meemaw/billing/subscription/resource/v1/SubscriptionResource.java
- backend/billing/billing-api/src/main/java/com/meemaw/billing/webhook/resource/v1/stripe/StripeWebhookResource.java
- backend/billing/billing-api/src/main/java/com/meemaw/billing/webhook/service/stripe/StripeWebhookProcessor.java
- backend/billing/billing-api/src/main/java/com/meemaw/billing/webhook/service/stripe/StripeWebhookTransformer.java
- backend/billing/billing-api/src/test/java/com/meemaw/billing/AbstractStripeTest.java
- backend/billing/billing-api/src/test/java/com/meemaw/billing/service/stripe/StripeBillingServiceTest.java
- backend/billing/billing-api/src/test/java/com/meemaw/billing/subscription/resource/v1/SubscriptionResourceImplTest.java
- backend/billing/billing-api/src/test/java/com/meemaw/billing/webhook/resource/v1/stripe/StripeWebhookResourceImplTest.java
**What**:
**Why**:
**How**:
**Checklist**:
> feat(backend/billing-api): finalize docs

- frontend/app/e2e/pages/SignUp.ts
- frontend/app/src/modules/auth/pages/LoginPage/LoginPage.spec.tsx
- frontend/app/src/modules/auth/pages/LoginPage/LoginPage.tsx
- frontend/shared/elements/src/atoms/UnstyledLink/UnstyledLink.tsx
- frontend/try/src/components/GetStarted/GetStarted.stories.tsx
- frontend/try/src/components/GetStarted/GetStarted.tsx
- frontend/try/src/components/GetStarted/index.ts
- frontend/try/src/components/SignUpForm/SignUpForm.stories.tsx
- frontend/try/src/components/SignUpForm/SignUpForm.tsx
- frontend/try/src/components/SignUpForm/index.ts
- frontend/try/src/components/Topbar/Topbar.tsx
- frontend/try/src/components/Topbar/index.ts
- frontend/try/src/pages/index.tsx
- frontend/try/src/pages/signup-confirm.tsx
**What**:
**Why**:
**How**:
**Checklist**:
> frontend: pass redirect to signup

- .github/workflows/frontend:app:pr.yml
- .github/workflows/frontend:homepage:pr.yml
- .github/workflows/frontend:try:pr.yml
- infrastructure/terraform/modules/storybook/main.tf
**What**:
**Why**:
**How**:
**Checklist**:
> infra: serve storybooks from cloudfront

- .github/workflows/backend:api-reference.yml
- infrastructure/terraform/internal/api-reference/main.tf
- infrastructure/terraform/modules/s3_restrict_access_to_cloudfront/main.tf
- infrastructure/terraform/modules/s3_restrict_access_to_cloudfront/outputs.tf
- infrastructure/terraform/modules/s3_restrict_access_to_cloudfront/variables.tf
- infrastructure/terraform/modules/s3_restrict_access_to_cloudfront/versions.tf
- infrastructure/terraform/modules/storybook/main.tf
**What**:
**Why**:
**How**:
**Checklist**:
> infra: docs cloudfront

- backend/auth/auth-api/src/main/java/com/meemaw/auth/organization/service/OrganizationInviteService.java
- backend/auth/auth-api/src/main/java/com/meemaw/auth/organization/service/impl/OrganizationInviteServiceImpl.java
- backend/auth/auth-api/src/test/java/com/meemaw/auth/organization/resource/v1/OrganizationResourceImplTest.java
- backend/shared/shared-sdk/src/main/java/com/rebrowse/model/organization/TeamInvite.java
- backend/shared/shared-sdk/src/main/java/com/rebrowse/model/organization/TeamInviteAcceptParams.java
- backend/shared/shared-sdk/src/main/java/com/rebrowse/net/RebrowseHttpClient.java
**What**:
**Why**:
**How**:
**Checklist**:
> fix(backend/auth-api): team invite accept should store user password

- backend/gradle.properties
- backend/local-test-services/docker-compose.yml
- backend/shared/testing-utils/src/main/java/com/meemaw/test/testconainers/elasticsearch/ElasticsearchTestContainer.java
**What**:
**Why**:
**How**:
**Checklist**:
> chore(deps): bump elastic

- infrastructure/k8/development/atlantis.yaml
- infrastructure/k8/development/helmfile.yaml
- infrastructure/terraform/modules/browser/main.tf
**What**:
**Why**:
**How**:
**Checklist**:
> chore(deps): bump atlantis

- frontend/app/package.json
- frontend/shared/elements/package.json
- frontend/try/package.json
- package.json
- yarn.lock
**What**:
**Why**:
**How**:
**Checklist**:
> chore(deps): bump various frontend

- .github/workflows/frontend:app:pr:e2e.yml
- backend/local-test-services/docker-compose.yml
**What**:
**Why**:
**How**:
**Checklist**:
> chore: stripe compose

- .github/workflows/frontend:preview.yml
**What**:
**Why**:
**How**:
**Checklist**:
> chore: stable pr number

- .github/workflows/frontend:preview.yml
**What**:
**Why**:
**How**:
**Checklist**:
> chore :sls remove

- .github/workflows/frontend:preview.yml
**What**:
**Why**:
**How**:
**Checklist**:
> chore: build before deploy

- .github/workflows/frontend:preview.yml
**What**:
**Why**:
**How**:
**Checklist**:
> Build before 2

- .github/workflows/frontend:preview.yml
**What**:
**Why**:
**How**:
**Checklist**:
> chore: sls no debug

- .github/workflows/frontend:preview.yml
- frontend/shared/previews/route53-change-set.json
- frontend/shared/previews/serverless.yml
- infrastructure/terraform/internal/previews/dns.tf
- infrastructure/terraform/internal/previews/storage.tf
**What**:
**Why**:
**How**:
**Checklist**:
> chore: try-previews

- .github/workflows/docker.yml
- backend/auth/auth-api/src/main/java/com/meemaw/auth/sso/session/service/SsoServiceImpl.java
- backend/auth/auth-api/src/main/java/com/meemaw/auth/tfa/TfaProvider.java
- backend/auth/auth-api/src/main/java/com/meemaw/auth/tfa/challenge/resource/v1/TfaChallengeResourceImpl.java
- backend/auth/auth-api/src/main/java/com/meemaw/auth/tfa/challenge/service/TfaChallengeService.java
- backend/auth/auth-api/src/main/java/com/meemaw/auth/tfa/setup/resource/v1/TfaSetupResourceImpl.java
- backend/auth/auth-api/src/main/java/com/meemaw/auth/tfa/sms/impl/TfaSmsProvider.java
- backend/auth/auth-api/src/main/java/com/meemaw/auth/tfa/totp/impl/TfaTotpProvider.java
- backend/auth/auth-api/src/main/java/com/meemaw/auth/user/phone/datasource/HazelcastUserPhoneCodeDatasource.java
- backend/auth/auth-api/src/main/java/com/meemaw/auth/user/phone/datasource/UserPhoneCodeDatasource.java
- backend/auth/auth-api/src/main/java/com/meemaw/auth/user/phone/service/UserPhoneCodeService.java
- backend/auth/auth-api/src/main/java/com/meemaw/auth/user/resource/v1/UserResourceImpl.java
- backend/auth/auth-api/src/main/java/com/meemaw/auth/user/service/UserService.java
- backend/auth/auth-api/src/test/java/com/meemaw/auth/tfa/challenge/resource/v1/TfaChallengeResourceImplTest.java
**What**:
**Why**:
**How**:
**Checklist**:
> fix(backend/auth-api): split tfa code cache keys

- .github/workflows/frontend:preview.yml
**What**:
**Why**:
**How**:
**Checklist**:
> chore: delete cf distro

- .github/workflows/frontend:preview.yml
**What**:
**Why**:
**How**:
**Checklist**:
> Cleanup lambdas

- .github/workflows/frontend:preview.yml
**What**:
**Why**:
**How**:
**Checklist**:
> chore(ci): retry deleteing lambda @ edge until it succeds

- .github/workflows/frontend:app:pr:e2e.yml
- .github/workflows/frontend:preview.yml
- backend/auth/auth-api-contracts/src/main/java/com/meemaw/auth/tfa/setup/resource/v1/TfaSetupResource.java
- backend/auth/auth-api/src/main/java/com/meemaw/auth/organization/resource/v1/OrganizationTeamInviteResourceImpl.java
- backend/auth/auth-api/src/main/java/com/meemaw/auth/signup/resource/v1/SignUpResourceImpl.java
- backend/auth/auth-api/src/main/java/com/meemaw/auth/sso/session/service/SsoService.java
- backend/auth/auth-api/src/main/java/com/meemaw/auth/sso/session/service/SsoServiceImpl.java
- backend/auth/auth-api/src/main/java/com/meemaw/auth/tfa/setup/resource/v1/TfaSetupResourceImpl.java
- backend/auth/auth-api/src/test/java/com/meemaw/auth/signup/resource/v1/SignUpResourceImplTest.java
- backend/local-test-services/docker-compose.yml
- backend/shared/testing-utils/src/main/java/com/meemaw/test/setup/AuthApiTestProvider.java
- frontend/app/e2e/pages/settings/organization/OrganizationSubscriptionSettingsPage.ts
- frontend/app/e2e/specs/settings/organization/organization-auth-settings.e2e.ts
**What**:
**Why**:
**How**:
**Checklist**:
> feat(backend/auth-api): 2fa finalize

- backend/auth/auth-api/src/test/java/com/meemaw/auth/sso/saml/resource/v1/SamlResourceImplTest.java
- backend/auth/auth-api/src/test/java/com/meemaw/auth/sso/session/resource/v1/SsoSessionResourceImplTest.java
- backend/auth/auth-api/src/test/java/com/meemaw/auth/tfa/challenge/resource/v1/TfaChallengeResourceImplTest.java
- backend/shared/shared-sdk/src/main/java/com/rebrowse/Rebrowse.java
- backend/shared/shared-sdk/src/main/java/com/rebrowse/model/SearchParam.java
- backend/shared/shared-sdk/src/main/java/com/rebrowse/model/SearchParamSerializer.java
- backend/shared/shared-sdk/src/main/java/com/rebrowse/model/TermOperation.java
- backend/shared/shared-sdk/src/main/java/com/rebrowse/model/auth/ApiKey.java
- backend/shared/shared-sdk/src/main/java/com/rebrowse/model/auth/SsoSetup.java
- backend/shared/shared-sdk/src/main/java/com/rebrowse/model/auth/UserData.java
- backend/shared/shared-sdk/src/main/java/com/rebrowse/model/organization/Organization.java
- backend/shared/shared-sdk/src/main/java/com/rebrowse/model/organization/PasswordPolicy.java
- backend/shared/shared-sdk/src/main/java/com/rebrowse/model/organization/TeamInvite.java
- backend/shared/shared-sdk/src/main/java/com/rebrowse/model/session/Session.java
- backend/shared/shared-sdk/src/main/java/com/rebrowse/model/session/SessionPage.java
- backend/shared/shared-sdk/src/main/java/com/rebrowse/model/session/UserAgent.java
- backend/shared/shared-sdk/src/main/java/com/rebrowse/model/user/User.java
- backend/shared/shared-sdk/src/main/java/com/rebrowse/model/user/UserSearchParams.java
- backend/shared/shared-sdk/src/main/java/com/rebrowse/net/ApiResource.java
- backend/shared/shared-sdk/src/main/java/com/rebrowse/net/HttpClient.java
- backend/shared/shared-sdk/src/main/java/com/rebrowse/net/NetHttpClient.java
- backend/shared/shared-sdk/src/main/java/com/rebrowse/net/RawHttpClient.java
- backend/shared/shared-sdk/src/main/java/com/rebrowse/net/ReadValue.java
- backend/shared/shared-sdk/src/main/java/com/rebrowse/net/RebrowseHttpClient.java
- backend/shared/shared-sdk/src/main/java/com/rebrowse/net/RebrowseRequest.java
- backend/shared/shared-sdk/src/main/java/com/rebrowse/net/RequestOptions.java
- backend/shared/shared-sdk/src/main/java/com/rebrowse/util/FormEncoder.java
**What**:
**Why**:
**How**:
**Checklist**:
> feat(backend/sdk): support query param search

- .github/workflows/backend:check.yml
- frontend/app/.storybook/main.js
- frontend/homepage/.storybook/main.js
- frontend/shared/elements/.storybook/main.js
- frontend/shared/next-storybook/package.json
- frontend/shared/storybook/package.json
- frontend/try/.storybook/main.js
- yarn.lock
**What**:
**Why**:
**How**:
**Checklist**:
> fix(ci): new path envs

- .github/workflows/backend:check.yml
- .github/workflows/backend:test.yml
- backend/.idea/codeStyles/Project.xml
- backend/auth/auth-api/src/main/java/com/meemaw/auth/core/App.java
- backend/auth/auth-api/src/main/java/com/meemaw/auth/organization/service/OrganizationTeamInviteService.java
- backend/auth/auth-api/src/main/java/com/meemaw/auth/sso/oauth/AbstractOAuthIdentityProvider.java
- backend/auth/auth-api/src/main/java/com/meemaw/auth/sso/saml/resource/v1/SamlResourceImpl.java
- backend/auth/auth-api/src/main/java/com/meemaw/auth/sso/session/datasource/hazelcast/HazelcastSsoSessionDatasource.java
- backend/auth/auth-api/src/main/resources/application.properties
- backend/auth/auth-api/src/test/java/com/meemaw/auth/core/resource/cors/CorsTest.java
- backend/auth/auth-api/src/test/java/com/meemaw/auth/organization/resource/v1/OrganizationResourceImplTest.java
- backend/beacon/beacon-api/src/main/java/com/meemaw/beacon/core/App.java
- backend/beacon/beacon-api/src/main/java/com/meemaw/beacon/service/BeaconService.java
- backend/billing/billing-api/src/main/java/com/meemaw/billing/core/App.java
- backend/billing/billing-api/src/main/resources/application.properties
- backend/billing/billing-api/src/test/java/com/meemaw/billing/core/resource/cors/CorsTest.java
- backend/build.gradle
- backend/gradle.properties
- backend/local-test-services/docker-compose.yml
- backend/session/session-api/src/main/java/com/meemaw/session/core/App.java
- backend/session/session-api/src/main/java/com/meemaw/session/location/model/dto/IpStackLocationDTO.java
- backend/session/session-api/src/main/java/com/meemaw/session/location/service/impl/LocationServiceImpl.java
- backend/shared/testing-utils/src/main/java/com/meemaw/test/testconainers/elasticsearch/ElasticsearchTestContainer.java
**What**:
**Why**:
**How**:
**Checklist**:
> Ci fix backend tests

- .github/workflows/frontend:app:master.yml
- .github/workflows/frontend:homepage:master.yml
- .github/workflows/frontend:try:master.yml
- .github/workflows/frontend:try:pr:e2e.yml
**What**:
**Why**:
**How**:
**Checklist**:
> chore: storybook master setup

- .github/workflows/frontend:app:master.yml
- .github/workflows/frontend:homepage:master.yml
- .github/workflows/frontend:try:master.yml
- frontend/shared/storybook/.storybook/main.js
**What**:
**Why**:
**How**:
**Checklist**:
> chore: sb extract

- frontend/app/package.json
- frontend/app/src/test/pages/login/index.spec.ts
- frontend/browser/bootstrap/src/index.spec.ts
- frontend/shared/testing/src/setup.ts
- yarn.lock
**What**:
**Why**:
**How**:
**Checklist**:
> Next page tester

- frontend/app/e2e/specs/settings/organization/organization-subscription-settings.e2e.ts
- frontend/app/src/modules/billing/hooks/useActivePlan.ts
- frontend/app/src/modules/billing/hooks/useInvoices.ts
- frontend/app/src/modules/billing/hooks/useSubscription.ts
- frontend/app/src/modules/billing/hooks/useSubscriptions.ts
- frontend/app/src/modules/settings/components/organization/BillingSubscription/BillingSubscription.tsx
- frontend/app/src/modules/settings/pages/organization/OrganizationSettingsBillingSubscriptionDetailsPage/OrganizationSettingsBillingSubscriptionDetailsPage.tsx
- frontend/app/src/modules/settings/pages/organization/OrganizationSettingsBillingSubscriptionPage/OrganizationSettingsBillingSubscriptionPage.tsx
- frontend/app/src/shared/hooks/useQuery/index.ts
- frontend/app/src/shared/hooks/useQuery/useQuery.ts
- infrastructure/k8/monitoring/grafana.yaml
Fixes https://github.com/insights-io/Insight/issues/929
> fix(frontend/app): billing react-query

- .github/workflows/docker.yml
- .github/workflows/frontend:preview.yml
- frontend/homepage/.env.development
- frontend/homepage/.env.development.docker
- frontend/homepage/.env.production
- frontend/homepage/next.config.js
- frontend/homepage/package.json
- frontend/homepage/src/modules/home/pages/HomePage/HomePage.spec.tsx
- frontend/homepage/src/modules/home/pages/HomePage/HomePage.tsx
- frontend/homepage/src/pages/_document.tsx
- frontend/homepage/src/pages/api/[...slug].ts
- frontend/homepage/src/pages/index.tsx
- frontend/shared/previews/serverless.yml
- infrastructure/terraform/internal/previews/dns.tf
**What**:
**Why**:
**How**:
**Checklist**:
> infra: homepage preview

- backend/auth/auth-api/src/main/java/com/meemaw/auth/mfa/setup/resource/v1/MfaSetupResourceImpl.java
- backend/auth/auth-api/src/main/java/com/meemaw/auth/mfa/sms/impl/MfaSmsProvider.java
- backend/auth/auth-api/src/main/java/com/meemaw/auth/mfa/totp/impl/MfaTotpProvider.java
- backend/auth/auth-api/src/main/java/com/meemaw/auth/user/phone/service/UserPhoneCodeService.java
- backend/auth/auth-api/src/main/java/com/meemaw/auth/user/resource/v1/UserResourceImpl.java
- backend/auth/auth-api/src/main/java/com/meemaw/auth/user/service/UserService.java
- backend/auth/auth-api/src/test/java/com/meemaw/auth/mfa/challenge/resource/v1/MfaChallengeResourceImplTest.java
- backend/auth/auth-api/src/test/java/com/meemaw/auth/mfa/setup/resource/v1/MfaSetupResourceImplTest.java
- backend/auth/auth-api/src/test/java/com/meemaw/auth/user/resource/v1/UserResourceImplTest.java
- backend/auth/auth-model/src/main/java/com/meemaw/auth/sso/session/model/AuthPrincipal.java
- frontend/app/src/modules/settings/components/account/ChangePassword/ChangePassword.tsx
- frontend/app/src/modules/settings/hooks/useAuthTokens.ts
- frontend/app/src/modules/settings/pages/account/AccountSettingsAuthTokensPage/AccountSettingsAuthTokensPage.tsx
**What**:
**Why**:
**How**:
**Checklist**:
> feat(frontend/app): change password panel

- backend/auth/auth-api-contracts/src/main/java/com/meemaw/auth/sso/session/resource/v1/SsoSessionResource.java
- backend/auth/auth-api/src/main/java/com/meemaw/auth/organization/service/OrganizationTeamInviteService.java
- backend/auth/auth-api/src/main/java/com/meemaw/auth/sso/session/resource/v1/SsoSessionResourceImpl.java
- backend/session/session-api/src/main/java/com/meemaw/session/sessions/datasource/sql/SqlSessionDatasource.java
- backend/session/session-api/src/main/resources/application.properties
- backend/session/session-api/src/test/java/com/meemaw/session/core/resource/cors/CorsTest.java
- backend/shared/shared-sql/src/main/java/com/meemaw/shared/sql/rest/query/SQLFilterExpression.java
- frontend/app/e2e/pages/Verification.ts
- frontend/app/e2e/pages/settings/account/AccountSettingsDetailsPage.ts
- frontend/app/e2e/pages/settings/account/AccountSettingsSecurityPage.ts
- frontend/app/e2e/pages/settings/account/TimeBasedTwoFactorAuthenticationSetupModal.ts
- frontend/app/e2e/specs/login/verification.e2e.ts
- frontend/app/e2e/specs/settings/account/details.e2e.ts
**What**:
**Why**:
**How**:
**Checklist**:
> fix: e2e tests

- .github/workflows/frontend:app:pr:e2e.yml
- .github/workflows/frontend:browser:tracking.yml
- backend/auth/auth-api/src/test/java/com/meemaw/auth/core/resource/health/HealthCheckTest.java
- backend/beacon/beacon-api/build.gradle
- backend/beacon/beacon-api/migrations/kafka/topics/events-unload.yaml
- backend/beacon/beacon-api/migrations/kafka/topics/events.yaml
- backend/beacon/beacon-api/src/main/java/com/meemaw/beacon/resource/v1/BeaconResource.java
- backend/beacon/beacon-api/src/main/resources/application.properties
- backend/beacon/beacon-api/src/test/java/com/meemaw/beacon/resource/v1/BeaconBeatResourceValidationTest.java
- backend/billing/billing-api/src/test/java/com/meemaw/billing/core/resource/health/HealthCheckTest.java
- backend/events/events-model/build.gradle
- backend/gradle.properties
- backend/local-test-services/docker-compose.yml
- backend/local-test-services/kafka/cluster.yaml
- backend/session/session-api/build.gradle
- backend/session/session-api/src/main/java/com/meemaw/session/pages/service/PageService.java
- backend/session/session-api/src/main/java/com/meemaw/session/sessions/datasource/sql/SqlSessionDatasource.java
- backend/session/session-api/src/main/java/com/meemaw/session/sessions/service/SessionSocketService.java
- backend/session/session-api/src/test/java/com/meemaw/session/core/resource/health/HealthCheckTest.java
- backend/session/session-api/src/test/java/com/meemaw/session/insights/resource/v1/InsightResourceImplTest.java
- backend/shared/rest-api/build.gradle
- backend/shared/rest/build.gradle
- backend/shared/shared-sql/build.gradle
- backend/shared/shared-sql/src/main/java/com/meemaw/shared/sql/rest/query/SQLFilterExpression.java
- backend/shared/shared-sql/src/main/java/com/meemaw/shared/sql/rest/query/SQLGroupByQuery.java
- backend/shared/shared-sql/src/main/java/com/meemaw/shared/sql/rest/query/SQLTermFilterExpression.java
- backend/shared/testing-utils/src/main/java/com/meemaw/test/testconainers/kafka/KafkaTestContainer.java
- frontend/shared/sdk/src/sessions/resource.ts
**What**:
**Why**:
**How**:
**Checklist**:
> chore: bump quarkus to v1.10.2

- backend/local-test-services/docker-compose.yml
- infrastructure/kafka/k8/migrations.yaml
- skaffold.yaml
**What**:
**Why**:
**How**:
**Checklist**:
> feat: k8 kafka migrations

- backend/local-test-services/docker-compose.yml
- infrastructure/kafka/cluster.yaml
- infrastructure/kafka/k8/migrations.yaml
**What**:
**Why**:
**How**:
**Checklist**:
> fix: kafka-zookeeper dns

- .github/workflows/backend:test.yml
- backend/build.gradle
- backend/gradle/ci-support.gradle
- backend/shared/testing-utils/src/main/java/com/meemaw/test/testconainers/kafka/KafkaTestContainer.java
**What**:
**Why**:
**How**:
**Checklist**:
> ci: run backend tests in parallel

- backend/beacon/beacon-api/src/main/resources/application.properties
- backend/beacon/beacon-api/src/test/java/com/meemaw/beacon/core/resource/health/HealthCheckTest.java
- backend/shared/testing-utils/src/main/java/com/meemaw/test/testconainers/TestContainerApiDependency.java
- backend/shared/testing-utils/src/main/java/com/meemaw/test/testconainers/api/AbstractApiTestContainer.java
- backend/shared/testing-utils/src/main/java/com/meemaw/test/testconainers/api/Api.java
- backend/shared/testing-utils/src/main/java/com/meemaw/test/testconainers/api/auth/AuthApiTestContainer.java
- backend/shared/testing-utils/src/main/java/com/meemaw/test/testconainers/elasticsearch/ElasticsearchMigrationsTestContainer.java
- backend/shared/testing-utils/src/main/java/com/meemaw/test/testconainers/elasticsearch/ElasticsearchTestContainer.java
- backend/shared/testing-utils/src/main/java/com/meemaw/test/testconainers/kafka/KafkaTestContainer.java
- backend/shared/testing-utils/src/main/java/com/meemaw/test/testconainers/kafka/KafkaTestExtension.java
- backend/shared/testing-utils/src/main/java/com/meemaw/test/testconainers/pg/PostgresTestContainer.java
- backend/shared/testing-utils/src/main/java/com/meemaw/test/testconainers/pg/PostgresTestExtension.java
- package.json
- yarn.lock
**What**:
**Why**:
**How**:
**Checklist**:
> Fix beacon api tests

- .github/workflows/frontend:preview.yml
**What**:
**Why**:
**How**:
**Checklist**:
> ci: fix homepage preview cleanup

- backend/auth/auth-model/src/main/java/com/meemaw/auth/user/UserRegistry.java
- backend/gradle.properties
- backend/session/session-api-contracts/src/main/java/com/meemaw/session/insights/resource/v1/InsightsResource.java
- backend/session/session-api-contracts/src/main/java/com/meemaw/session/sessions/resource/v1/SessionResource.java
- backend/session/session-api/src/main/java/com/meemaw/session/insights/resource/v1/InsightsResourceImpl.java
- backend/session/session-api/src/main/java/com/meemaw/session/sessions/datasource/sql/SqlSessionDatasource.java
- backend/session/session-api/src/main/java/com/meemaw/session/sessions/resource/v1/SessionResourceImpl.java
- backend/session/session-api/src/test/java/com/meemaw/session/insights/resource/v1/InsightResourceImplTest.java
- backend/session/session-api/src/test/java/com/meemaw/session/sessions/resource/v1/AbstractSessionResourceTest.java
- backend/session/session-api/src/test/java/com/meemaw/session/sessions/resource/v1/SessionResourceImplTest.java
- backend/shared/rest-core/src/main/java/com/rebrowse/api/RebrowseApi.java
- backend/shared/rest/src/main/java/com/meemaw/shared/rest/query/AbstractQueryParser.java
- backend/shared/rest/src/main/java/com/meemaw/shared/rest/query/SearchDTO.java
- backend/shared/rest/src/main/java/com/meemaw/shared/rest/query/TimePrecision.java
- backend/shared/rest/src/main/java/com/meemaw/shared/rest/query/rhs/colon/RHSColonParser.java
- backend/shared/shared-sql/src/main/java/com/meemaw/shared/sql/rest/query/DatetimeFunctions.java
- backend/shared/shared-sql/src/main/java/com/meemaw/shared/sql/rest/query/SQLGroupByQuery.java
- backend/shared/shared-sql/src/main/java/com/meemaw/shared/sql/rest/query/SQLSearchDTO.java
- frontend/shared/sdk/src/sessions/resource.ts
**What**:
**Why**:
**How**:
**Checklist**:
> feat(session-api): count by created_at

- backend/shared/testing-utils/build.gradle
Fixes https://github.com/insights-io/Insight/issues/906
> fix: disable testing-utils quarkus-build gradle task

- frontend/app/e2e/pages/settings/organization/OrganizationSecuritySettingsPage.ts
- frontend/app/e2e/specs/_app.e2e.ts
- frontend/app/e2e/specs/sessions.e2e.ts
- frontend/app/src/__tests__/mocks/index.ts
- frontend/app/src/__tests__/pages/settings/account/details/index.spec.ts
- frontend/app/src/__tests__/pages/settings/account/index.spec.ts
- frontend/app/src/__tests__/pages/settings/organization/members/invites/index.spec.ts
- frontend/app/src/__tests__/pages/settings/organization/security/index.spec.ts
- frontend/app/src/settings/components/organization/TeamInviteModal/TeamInviteModal.tsx
- frontend/app/src/settings/pages/account/AccountSettingsDetailsPage/AccountSettingsDetailsPage.stories.tsx
- frontend/app/src/settings/pages/organization/OrganizationSettingsSecurityPage/OrganizationSettingsSecurityPage.stories.tsx
- frontend/app/src/settings/pages/organization/OrganizationSettingsSecurityPage/PasswordPolicyForm.tsx
- frontend/app/src/shared/hooks/useOrganizationPasswordPolicy.ts
- frontend/shared/sdk/src/auth/user/resource.ts
- frontend/shared/sdk/src/auth/user/types.ts
**What**:
**Why**:
**How**:
**Checklist**:
> test: /settings/organization/security
